### PR TITLE
swapped 'split' for 'explode' for php7 compatibility

### PR DESCRIPTION
**Pull request by dericcrago**

### CODE REVIEW

**Comment by jrchamp** [comment]
#21 contains this change and more.

**Comment by dericcrago** [comment]
@jrchamp - that's great, but #21 has been open for like a year now, right? For anyone looking for PHP 7 compatibility, I think swapping ``split`` for ``explode`` is the only necessary change. I don't really have a preference of how, but it'd be nice for https://wordpress.org/plugins/shibboleth/ to support PHP 7.

**Comment by jrchamp** [comment]
@dericcrago You are correct. I mentioned #21 so that anyone who arrives here might benefit from some of the other WordPress, PHP Notice and Multisite benefits present in that PR. Unfortunately, the plugin owners are not regularly responding to these requests. It would be nice to have an active maintainer added to the plugin.

**Comment by srguglielmo** [comment]
Or use a maintained plugin.

*cough cough* SimpleShib

(Disclaimer: I'm the author/maintainer of it)

**Comment by michaelryanmcneill** [comment]
Hello, thank you for reporting this issue. I released version 1.8 today to resolve this and other issues. I am the new maintainer of the plugin and all further work on the plugin will be done in a new [GitHub repository](https://github.com/michaelryanmcneill/shibboleth/). If you have any further issues, please don't hesitate to report them in the new repository.

**Comment by dericcrago** [comment]
thanks @michaelryanmcneill

**Pull request closed without merging**
